quarkus:
  banner:
    enabled: false
  hibernate-orm:
    database:
      generation: none

mp:
  openapi:
    extensions:
      smallrye:
        info:
          title: Value Mapping API
          version: 0.0.1
          description: API for retrieving value mappings
          contact:
            email: techsupport@redhat.com
            name: Value Mapping API Support
            url: https://github.com/stephennimmo/value-mapping-api
          license:
            name: Apache 2.0
            url: http://www.apache.org/licenses/LICENSE-2.0.html